### PR TITLE
Initial version of privacy policy update

### PR DESCRIPTION
**Pull request by florianschmidt1994**

### CODE REVIEW

**Comment by florianschmidt1994** [comment]
Pls use `Table Layout` in Tailwindcss for this so we can drop the dependency @tgraupne

**Comment by tgraupne** [comment]
Hey team ❤️ this PR basically contains the wording of our new privacy policy page and I did my best in terms of formatting it 🙈

I'd like to ask our web experts if they could take a look and give some feedback, maybe even suggestion on how one would format this page in 2020?

@mauriceackel @jagaSto @kenodressel

**Comment by florianschmidt1994** [comment]
I like the formatting so far, but I would think about replacing the table by paragraphs structured with different headlines. I've toyed around a bit with the table and different layouts on mobile and non of them seem satisfatory so far

**Comment by mauriceackel** [comment]
Just took a shot at it and removed the dependency. Pls review :)

**Comment by florianschmidt1994** [comment]
Looks good to me. Pls remove the dependency from the lock file as well :)

**Pull request merged**
